Use pipenv for package management
pacificclimate/crmprtd pull request #100
Opened 2021-08-11 18:51 UTC by jameshiebert

I have a branch going here that seems to address everything with respect to the migration from using `pip` to `pipenv`. The only catch, is that I had to remove the `Pipfile.lock` to be able to support testing on multiple version of Python (in this case 3.6, 3.7, and 3.8). If there's a way around this, I'm happy to hear about it, but [this blog post](https://dev.to/tomoyukiaota/creating-a-pipfile-for-multiple-versions-of-python-9f2) seems to indicate that there's not, and `pipenv` doesn't seem to have any mechanisms to specify a lock file at install time.

Resolves #99

2021-08-16 19:10 UTC, nikola-rados requested changes
This looks good overall, nice work! You brought some important items to my attention which will help us improve other projects. Since you have posted this PR we have made some progress on how we tackle multiple python versions. For reference you can look at [`orca`](https://github.com/pacificclimate/orca/blob/main/.github/workflows/python-ci.yml) to help adapt your work here.

2021-08-16 19:10 UTC, nikola-rados commented on .github/workflows/python-ci.yml
> +        pipenv install --python ${{ matrix.python-version }} --dev
A lot of this will be impacted by the python version handling.

2021-08-17 21:00 UTC, jameshiebert commented on README.md
> +pipenv install --dev .
Well... I specifically do *not* want to install it in "editable" mode for testing. There are cases where you can have a file in your source repository path, but not included in your `setup.py`. If you test in editable mode, the tests will pass, but the code won't work when the package gets built and installed. Testing outside of editable mode avoids that.

2021-08-18 16:46 UTC, jameshiebert commented
OK, I *think* I've addressed all of your comments and brought this to be parallel to the `orca` implementation. Any other comments or concerns?

2021-08-18 16:47 UTC, nikola-rados approved these changes
LGTM!

2021-08-18 16:48 UTC, merged