I 135 pyproject.toml
pacificclimate/crmprtd pull request #140
Opened 2023-01-28 00:08 UTC by rod-glover

Resolves #135

2023-01-30 21:07 UTC, jameshiebert requested changes
Looks mostly good, but I think that you'll need to make some changes to the PyPI Publish action in `.github/workflows/pypi-publish.yml`. It still uses Python 3.6 and invokes `setup.py`. You'll probably want to temporarily change the "on: push: tags" so that you can test it before the next numbered release.

2023-01-30 21:07 UTC, jameshiebert commented on pyproject.toml
> +    {name = "Nic Rados"}
Nik

2023-01-30 21:07 UTC, jameshiebert commented on pyproject.toml
> +description = "Utility to download Environment Canada MPO-XML and insert it into PCIC's database"
Could update this description, since the utility is now broader than this.

2023-01-31 18:56 UTC, rod-glover commented
Good catch, James! I published a test version, numbered 4.1.0a, to our pypi server, then installed it using pip only in a fresh virtual env. Install looked OK: `crmprtd_*` scripts were present and apparently working; contents of `venv/lib/python3.8/site-packages/` is as expected.

I'll remove the test setup from pypi-publish once you approve the PR.

2023-01-31 19:27 UTC, jameshiebert approved these changes
Looks great!

2023-01-31 19:43 UTC, merged